### ISSUE TITLE
Could not load commands after update from 3.0.6 to 3.0.17 

### ISSUE THREAD

**Issue by tanij** [duckietown/duckietown-shell#34]
Fixed by manually erasing `~/.dt-shell/commands`, as recommended by the script.

➜  ~ dts version
INFO:dts:duckietown-shell 3.0.17

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
ERROR:dts:

            !   Could not load commands.

                Cannot load command class 'challenges.info.command.DTCommand' (package='challenges.', command='info'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.reset.command.DTCommand' (package='challenges.', command='reset'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.retire.command.DTCommand' (package='challenges.', command='retire'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.list.command.DTCommand' (package='challenges.', command='list'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.update.command.DTCommand' (package='challenges.', command='update'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.submit.command.DTCommand' (package='challenges.', command='submit'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.evaluator.command.DTCommand' (package='challenges.', command='evaluator'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.config.command.DTCommand' (package='challenges.', command='config'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

Cannot load command class 'challenges.define.command.DTCommand' (package='challenges.', command='define'): Traceback (most recent call last):
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 371, in _load_commands
    klass = _load_class(spec)
  File "/home/jtani/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 474, in _load_class
    mod = __import__(components[0])
  File "/home/jtani/.dt-shell/commands/challenges/__init__.py", line 8, in <module>
    from .define import *
  File "/home/jtani/.dt-shell/commands/challenges/define/__init__.py", line 1, in <module>
    from .command import *
  File "/home/jtani/.dt-shell/commands/challenges/define/command.py", line 7, in <module>
    from dt_shell.remote import dtserver_challenge_define
ImportError: cannot import name dtserver_challenge_define

            !   To recover, you might want to delete the directory
            !
            !      ~/.dt-shell/commands
            !
            !
